[tox]
# envlist is the list of environments that are tested when `tox` is run without any option
# hyphens in an environment name are used to delimit factors
envlist = lint, test

[testenv]
commands =
    lint: ruff check .
    lint: black --check --diff .
    lint: isort --check --diff .
    lint: mypy .
    test: pytest {posargs:tests}
deps =
    lint: black
    lint: isort
    lint: mypy
    lint: pytest
    lint: ruff
    test: pytest
